#! /usr/bin/bash

file=sort_analysis

if [ -f $file.o ]; then
	rm -f $file.o
else
	echo "--------------------no object file------------------ "
fi

gcc $file.c -g -o $file 2> err.txt

if [ -f $file ]; then
	echo "-----------------running the object file--------------"
	gdb $file
else
	echo "No executable file"
fi 
