#! /usr/bin/bash

ERR_FILE_NAME=err.txt
if [ -f $ERR_FILE_NAME ]; then
	rm -f $ERR_FILE_NAME
fi

FILE_NAME=fxd_pt1
gcc $FILE_NAME.c -o $FILE_NAME.o 2> err.txt

if [ -f $FILE_NAME.o ]; then
	./$FILE_NAME.o
else
	echo "Errors in the compilation"
fi

