#! /usr/bin/bash

file=semaphore_tut
err_file=err
out_file=out

if [ -f $file.o ]; then
	rm -f $file.o
else
	echo "---------no object file present----------"
fi

echo "------ compiling the file --------"
gcc $file.c -o $file.o 2> $err_file.txt
echo "--------- compile finished -------"

if [ -f $file.o ]; then
	echo " compile sucessful "
	./$file.o > $out_file.txt
	cat $out_file.txt
else
	echo " --------- No object file present -------"
	echo " -------- opening  err.txt ----------"
	cat $err_file.txt | more
	echo " ----------Report end --------------"
fi
